# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/apaul/Aaron's Folder/University of Rochester/CSC_173/Project_5"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/apaul/Aaron's Folder/University of Rochester/CSC_173/Project_5"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/apaul/Aaron's Folder/University of Rochester/CSC_173/Project_5/CMakeFiles" "/Users/apaul/Aaron's Folder/University of Rochester/CSC_173/Project_5//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/apaul/Aaron's Folder/University of Rochester/CSC_173/Project_5/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Project_5

# Build rule for target.
Project_5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Project_5
.PHONY : Project_5

# fast build rule for target.
Project_5/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/build
.PHONY : Project_5/fast

Boolean.o: Boolean.c.o
.PHONY : Boolean.o

# target to build an object file
Boolean.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/Boolean.c.o
.PHONY : Boolean.c.o

Boolean.i: Boolean.c.i
.PHONY : Boolean.i

# target to preprocess a source file
Boolean.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/Boolean.c.i
.PHONY : Boolean.c.i

Boolean.s: Boolean.c.s
.PHONY : Boolean.s

# target to generate assembly for a file
Boolean.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/Boolean.c.s
.PHONY : Boolean.c.s

Circuit.o: Circuit.c.o
.PHONY : Circuit.o

# target to build an object file
Circuit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/Circuit.c.o
.PHONY : Circuit.c.o

Circuit.i: Circuit.c.i
.PHONY : Circuit.i

# target to preprocess a source file
Circuit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/Circuit.c.i
.PHONY : Circuit.c.i

Circuit.s: Circuit.c.s
.PHONY : Circuit.s

# target to generate assembly for a file
Circuit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/Circuit.c.s
.PHONY : Circuit.c.s

Gates.o: Gates.c.o
.PHONY : Gates.o

# target to build an object file
Gates.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/Gates.c.o
.PHONY : Gates.c.o

Gates.i: Gates.c.i
.PHONY : Gates.i

# target to preprocess a source file
Gates.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/Gates.c.i
.PHONY : Gates.c.i

Gates.s: Gates.c.s
.PHONY : Gates.s

# target to generate assembly for a file
Gates.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/Gates.c.s
.PHONY : Gates.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/main.c.s
.PHONY : main.c.s

strdup.o: strdup.c.o
.PHONY : strdup.o

# target to build an object file
strdup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/strdup.c.o
.PHONY : strdup.c.o

strdup.i: strdup.c.i
.PHONY : strdup.i

# target to preprocess a source file
strdup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/strdup.c.i
.PHONY : strdup.c.i

strdup.s: strdup.c.s
.PHONY : strdup.s

# target to generate assembly for a file
strdup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project_5.dir/build.make CMakeFiles/Project_5.dir/strdup.c.s
.PHONY : strdup.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Project_5"
	@echo "... Boolean.o"
	@echo "... Boolean.i"
	@echo "... Boolean.s"
	@echo "... Circuit.o"
	@echo "... Circuit.i"
	@echo "... Circuit.s"
	@echo "... Gates.o"
	@echo "... Gates.i"
	@echo "... Gates.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... strdup.o"
	@echo "... strdup.i"
	@echo "... strdup.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

